sudo: true
language: ruby
rvm:
  - jruby
  - 2.2.5
  - 2.3.1
env:
  - TEST_REFINEMENTS=true
  - TEST_REFINEMENTS=false
before_install: 
  - gem install bundler -v 1.12.5
  - curl -sSf https://static.rust-lang.org/rustup.sh | sudo sh -s -- --channel=nightly
  - bundle && bundle exec rake build_src && rake clean_src
script: bundle exec rake test
