sudo: true
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
env:
  - TEST_MONKEYPATCHES=true
  - TEST_MONKEYPATCHES=false
  - WITH_REGRESSION=true
before_install: 
  - gem install bundler -v 1.12.5
  - curl -sSf https://static.rust-lang.org/rustup.sh | sudo sh -s -- --channel=nightly
  - bundle && bundle exec rake build_src && rake clean_src
script: bundle exec rake test
